### ISSUE TITLE
Have you try to use this method deal with the explicit score prediction?

### ISSUE THREAD

**Issue by sshzhang** [tebesu/CollaborativeMemoryNetwork#3]
Hello authors:
   I have some  confused .  Have you use this method for explicit score prediction ?

**Comment by tebesu** [comment]
Yes we have tried for explicit rating prediction but it was unable to beat strong baselines like CF-NADE. If I remember correctly it may have been on par with AutoRec.

**Comment by sshzhang** [comment]
Thanks a lot
