### ISSUE TITLE
Have you test the proposed model on the movielens-1m data set?

### ISSUE THREAD

**Issue by chenjie04** [tebesu/CollaborativeMemoryNetwork#4]
Hello authors:
I have a question. did you test your proposed model on the movielense-1m data set? I got the worse result than the NeuMF model as the number of users, number of items and max_user_neighbors are quite different. Is that reasonable?
Citeulike-a
-----------------------------
num_users =  5551
num_items =  16980
max_user_neighbors =  311
-----------------------------
..............................
MovieLens 1M
-----------------------------
num_users =  6040
num_items =  3706
max_user_neighbors =  3405
-----------------------------

**Comment by tebesu** [comment]
No free lunch.

The performance varies based on its ability to leverage the neighborhood. Our model can be seen as a variant of NeuMF where we use a memory network instead of a MLP.

**Comment by chenjie04** [comment]
ok. thanks a lot!
