### ISSUE TITLE
Reinitialization of hop_mapping

### ISSUE THREAD

**Issue by IamAdiSri** [tebesu/CollaborativeMemoryNetwork#6]
https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/attention.py#L177

Is hop_mapping reinitialized for every memory hop? Why is it not initialized in the `__init__` function and then trained progressively?

**Comment by tebesu** [comment]
Each hop_mapping is a separate linear layer and the parameters are learned. Since this is TensorFlow the graph is built once where as PyTorch the graph is constructed on every pass.
