### ISSUE TITLE
Sharing item outputs

### ISSUE THREAD

**Issue by IamAdiSri** [tebesu/CollaborativeMemoryNetwork#7]
https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/cmn.py#L157
https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/cmn.py#L158

Why do we need to share these weights? I'm unable to see how these variables are being used.

**Comment by tebesu** [comment]
These are not be used. I believe I made a User and Item CMN variant which did not show much improvement.

**Comment by IamAdiSri** [comment]
https://github.com/tebesu/CollaborativeMemoryNetwork/blob/2c55efdcb9f46f5d0e869cbbe68ba15eafc2a2cb/util/cmn.py#L150

I believe this variable remains unused as well. Could you please confirm that?
